In [1]:
import pandas as pd 
import numpy as np
import  datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_product=pd.read_csv(r"C:\Users\Asus\Downloads\zoomev\empty\products.csv")
df_sale=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\empty\sales.csv',parse_dates=['sales_transaction_date'])
df_submail=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\empty\email_subject.csv')
df_email=pd.read_csv(r'C:\Users\Asus\Downloads\zoomev\emails.csv')
print(df_product)
print('n/')
print(df_sale)

    product_id                   model  year product_type  base_price  \
0            1                  FioNex  2010      scooter       63998   
1            2  FioNex Limited Edition  2011      scooter      127998   
2            3                  FioNex  2013      scooter       79998   
3            4               DeltaPlus  2014   automobile      920000   
4            5                  Parker  2014      scooter      111998   
5            6                  Corpel  2015   automobile      524000   
6            7                  Sprint  2016      scooter       95998   
7            8  Sprint Limited Edition  2017      scooter      111998   
8            9            SigniaSafari  2017   automobile      280000   
9           10               Zelito800  2017   automobile      686000   
10          11               DeltaPlus  2019   automobile      760000   
11          12           FioNex Zester  2019      scooter       55998   

   production_start_date production_end_date  
0  

In [3]:
df_sale['Date']=df_sale['sales_transaction_date'].dt.date

In [4]:
df_sale['Date']

0        2017-07-19
1        2017-08-14
2        2019-01-20
3        2017-05-09
4        2019-05-21
            ...    
37706    2019-04-06
37707    2019-03-30
37708    2019-05-25
37709    2019-05-13
37710    2019-05-28
Name: Date, Length: 37711, dtype: object

In [5]:
df_sale['Date']=pd.to_datetime(df_sale['Date'])
df_sale.dtypes

customer_id                        int64
product_id                         int64
sales_transaction_date    datetime64[ns]
channel                           object
dealership_id                     object
Date                      datetime64[ns]
dtype: object

## What is the cummulative sales volume ( in units) for the first 7 days between 10- 10 -2016 and 16-`10-2016

In [13]:
df_start=df_sale.loc[(df_sale['product_id'] == 7)&(df_sale['Date'] >= '2016-10-10') & (df_sale['Date'] <= '2016-10-16')]
df_start

customer_id  product_id sales_transaction_date     channel  \
669         32721           7    2016-10-16 02:34:00  dealership   
769         44019           7    2016-10-14 04:05:00    internet   
822         49856           7    2016-10-12 00:26:00  dealership   
1030        13393           7    2016-10-16 20:13:00  dealership   
1242        36534           7    2016-10-16 12:49:00  dealership   
...           ...         ...                    ...         ...   
6980        31307           7    2016-10-10 21:22:00    internet   
7077        45880           7    2016-10-11 04:09:00  dealership   
7222        46831           7    2016-10-15 00:59:00    internet   
7242        49226           7    2016-10-12 10:26:00    internet   
7249        35497           7    2016-10-10 04:21:00  dealership   

     dealership_id       Date  
669              5 2016-10-16  
769         Online 2016-10-14  
822             10 2016-10-12  
1030            19 2016-10-16  
1242             7 2016-10-16  
...            ...        ...  
6980        Online 2016-10-10  
7077             7 2016-10-11  
7222        Online 2016-10-15  
7242        Online 2016-10-12  
7249             2 2016-10-10  

[64 rows x 6 columns]

In [18]:
sale_per_day=np.array(df_start['Date'].value_counts())
sale_per_day

array([14, 10, 10, 10,  9,  6,  5], dtype=int64)

In [21]:
No_of_days=np.arange(1,8,1)
No_of_days

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
list_of_tuple=list(zip(No_of_days,sale_per_day))
df=pd.DataFrame(list_of_tuple,columns=['No_of_days','sale_per_day'])
df

No_of_days  sale_per_day
0           1            14
1           2            10
2           3            10
3           4            10
4           5             9
5           6             6
6           7             5

In [28]:
df['cum_sum']=np.cumsum(df['sale_per_day'])
df

No_of_days  sale_per_day  cum_sum
0           1            14       14
1           2            10       24
2           3            10       34
3           4            10       44
4           5             9       53
5           6             6       59
6           7             5       64

## On 20th Oct, What are the last 7 days' Cumulative sales of Sprint Scooter ( in units)

In [29]:
df_end=df_sale.loc[(df_sale['Date']>='2016-10-14')&(df_sale['Date']<='2016-10-20')&(df_end['product_id']==7)]
df_end

customer_id  product_id sales_transaction_date     channel  \
13           1039           7    2016-10-19 22:17:00  dealership   
264         37626           7    2016-10-19 18:45:00    internet   
425          8067           7    2016-10-18 11:44:00    internet   
557         21477           7    2016-10-17 00:34:00    internet   
606         27413           7    2016-10-18 07:54:00  dealership   
...           ...         ...                    ...         ...   
7101        15346           7    2016-10-18 21:45:00    internet   
7155        30808           7    2016-10-19 19:44:00  dealership   
7176        48597           7    2016-10-19 14:18:00  dealership   
7197        39451           7    2016-10-20 13:25:00    internet   
7222        46831           7    2016-10-15 00:59:00    internet   

     dealership_id       Date  
13               1 2016-10-19  
264         Online 2016-10-19  
425         Online 2016-10-18  
557         Online 2016-10-17  
606              2 2016-10-18  
...            ...        ...  
7101        Online 2016-10-18  
7155            17 2016-10-19  
7176             5 2016-10-19  
7197        Online 2016-10-20  
7222        Online 2016-10-15  

[71 rows x 6 columns]

In [30]:
sale_per_day=np.array(df_end['Date'].value_counts())
sale_per_day

array([14, 12, 11, 10, 10,  9,  5], dtype=int64)

In [31]:
No_of_days=np.arange(1,8,1)
No_of_days

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
list_of_tuple=list(zip(No_of_days,sale_per_day))
df1=pd.DataFrame(list_of_tuple,columns=['No_of_days','sale_per_day'])
df1

No_of_days  sale_per_day
0           1            14
1           2            12
2           3            11
3           4            10
4           5            10
5           6             9
6           7             5

In [35]:
df1['cum_sum']=np.cumsum(df['sale_per_day'])
df1

No_of_days  sale_per_day  cum_sum
0           1            14       14
1           2            12       26
2           3            11       37
3           4            10       47
4           5            10       57
5           6             9       66
6           7             5       71

In [36]:
np.array(df_end['Date'].value_counts().max())

array(14)

In [37]:
##On which date did the sales volume reach its highest point?
np.array(df_start['Date'].value_counts().max())

array(14)

## On 22 -10-2016 by what percentage cummulative sales of last 7 days dropped compared to last 7 days cummulative sales on 21-10-2016 ?

In [52]:
df_new=df_sale.loc[(df_sale['Date']>='2016-10-15')&(df_sale['Date']<='2016-10-21')&(df_sale['product_id']==7)]
df_new

customer_id  product_id sales_transaction_date     channel  \
13           1039           7    2016-10-19 22:17:00  dealership   
264         37626           7    2016-10-19 18:45:00    internet   
425          8067           7    2016-10-18 11:44:00    internet   
557         21477           7    2016-10-17 00:34:00    internet   
606         27413           7    2016-10-18 07:54:00  dealership   
...           ...         ...                    ...         ...   
7101        15346           7    2016-10-18 21:45:00    internet   
7155        30808           7    2016-10-19 19:44:00  dealership   
7176        48597           7    2016-10-19 14:18:00  dealership   
7197        39451           7    2016-10-20 13:25:00    internet   
7222        46831           7    2016-10-15 00:59:00    internet   

     dealership_id       Date  
13               1 2016-10-19  
264         Online 2016-10-19  
425         Online 2016-10-18  
557         Online 2016-10-17  
606              2 2016-10-18  
...            ...        ...  
7101        Online 2016-10-18  
7155            17 2016-10-19  
7176             5 2016-10-19  
7197        Online 2016-10-20  
7222        Online 2016-10-15  

[72 rows x 6 columns]

In [53]:
sale_per_day=np.array(df_new['Date'].value_counts())
sale_per_day

array([14, 12, 11, 10, 10,  9,  6], dtype=int64)

In [54]:
no_of_day=np.arange(1,8,1)
no_of_day

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
list_of_tuple=list(zip(no_of_day,sale_per_day))
df2=pd.DataFrame(list_of_tuple,columns=['no_of_day','sale_per_day'])
df2

no_of_day  sale_per_day
0          1            14
1          2            12
2          3            11
3          4            10
4          5            10
5          6             9
6          7             6

In [69]:
df2['cum_sum']=np.cumsum(df2['sale_per_day'])
df2

no_of_day  sale_per_day  cum_sum  sprint_growth
0          1            14       14            NaN
1          2            12       26      85.714286
2          3            11       37      42.307692
3          4            10       47      27.027027
4          5            10       57      21.276596
5          6             9       66      15.789474
6          7             6       72       9.090909

In [58]:
#df2.drop(['sprint_growth'],axis=1,inplace=True)
#df2

In [67]:
df2['sprint_growth']=df2['cum_sum'].pct_change(periods=1)*100
df2

no_of_day  sale_per_day  cum_sum  sprint_growth
0          1            14       14            NaN
1          2            12       26      85.714286
2          3            11       37      42.307692
3          4            10       47      27.027027
4          5            10       57      21.276596
5          6             9       66      15.789474
6          7             6       72       9.090909

In [59]:
df_new1=df_sale.loc[(df_sale['Date']>='2016-10-16')&(df_sale['Date']<='2016-10-22')&(df_sale['product_id']==7)]
df_new1

customer_id  product_id sales_transaction_date     channel  \
13           1039           7    2016-10-19 22:17:00  dealership   
264         37626           7    2016-10-19 18:45:00    internet   
425          8067           7    2016-10-18 11:44:00    internet   
557         21477           7    2016-10-17 00:34:00    internet   
606         27413           7    2016-10-18 07:54:00  dealership   
...           ...         ...                    ...         ...   
7065        18624           7    2016-10-17 15:54:00    internet   
7101        15346           7    2016-10-18 21:45:00    internet   
7155        30808           7    2016-10-19 19:44:00  dealership   
7176        48597           7    2016-10-19 14:18:00  dealership   
7197        39451           7    2016-10-20 13:25:00    internet   

     dealership_id       Date  
13               1 2016-10-19  
264         Online 2016-10-19  
425         Online 2016-10-18  
557         Online 2016-10-17  
606              2 2016-10-18  
...            ...        ...  
7065        Online 2016-10-17  
7101        Online 2016-10-18  
7155            17 2016-10-19  
7176             5 2016-10-19  
7197        Online 2016-10-20  

[64 rows x 6 columns]

In [60]:
sale_per_day=np.array(df_new1['Date'].value_counts())
sale_per_day

array([14, 12, 11, 10,  9,  6,  2], dtype=int64)

In [61]:
no_of_day=np.arange(1,8,1)
no_of_day

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
list_of_tuple=list(zip(no_of_day,sale_per_day))
df3=pd.DataFrame(list_of_tuple,columns=['no_of_day','sale_per_day'])
df3

no_of_day  sale_per_day
0          1            14
1          2            12
2          3            11
3          4            10
4          5             9
5          6             6
6          7             2

In [63]:
df3['cum_sum']=np.cumsum(df3['sale_per_day'])
df3

no_of_day  sale_per_day  cum_sum
0          1            14       14
1          2            12       26
2          3            11       37
3          4            10       47
4          5             9       56
5          6             6       62
6          7             2       64

In [65]:
df3['sprint_growth']=df2['cum_sum'].pct_change(periods=1)*100
df3

no_of_day  sale_per_day  cum_sum  sprint_growth
0          1            14       14            NaN
1          2            12       26      85.714286
2          3            11       37      42.307692
3          4            10       47      27.027027
4          5             9       56      21.276596
5          6             6       62      15.789474
6          7             2       64       9.090909